# Generated by Django 5.1.2 on 2024-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_profile_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
